name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: daliaMarzouk90/test_integration_with_lambda@main
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - uses: daliaMarzouk90/test_integration_with_lambda@main
      with:
          args: zip -qq -r ./bundle.zip ./
