name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: zip
      uses: daliaMarzouk90/test_integration_with_lambda@main
      with:
          args: zip -qq -r ./bundle.zip ./
