name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: daliaMarzouk90/test_integration_with_lambda@main
      with:
        python-version: '3.9'
    - run: python lambda_function.py
