on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
          args: zip -qq -r ./bundle.zip ./
    - name: default deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: upload zip
      run: aws lambda update-function-code --function-name  test-products-sqs-trigger --zip-file fileb://bundle.zip
    
